
//------> ./rtl.v
// ----------------------------------------------------------------------
//  HLS HDL:        Verilog Netlister
//  HLS Version:    2021.1/950854 Production Release
//  HLS Date:       Mon Aug  2 21:36:02 PDT 2021
//
//  Generated by:   msilvaol@mes
//  Generated date: Sat Apr  8 09:22:40 2023
// ----------------------------------------------------------------------

//
// ------------------------------------------------------------------
//  Design Unit:    efex_mle
// ------------------------------------------------------------------


module efex_mle (
  et, vld, code_out
);
  input [17:0] et;
  input vld;
  output [9:0] code_out;



endmodule



